# Generated by Django 5.0.6 on 2024-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('office_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('office_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tbl_office',
            },
        ),
    ]
