# Generated by Django 5.0.6 on 2024-08-22 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackIt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.IntegerField(max_length=15)),
                ('document_type', models.CharField(max_length=45)),
                ('category', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tbl_document_type',
            },
        ),
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('no', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('priority_level', models.CharField(max_length=16)),
                ('deadline', models.IntegerField(max_length=15)),
            ],
            options={
                'db_table': 'tbl_priority_level',
            },
        ),
        migrations.CreateModel(
            name='DocumentRoute',
            fields=[
                ('routing_no', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.office')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.documenttype')),
            ],
            options={
                'db_table': 'tbl_document_route',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_no', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('tracking_no', models.CharField(max_length=30)),
                ('qr_code', models.CharField(max_length=15)),
                ('next_route', models.CharField(max_length=45, null=True)),
                ('subject', models.CharField(max_length=120)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=25)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.documenttype')),
                ('priority_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.prioritylevel')),
            ],
            options={
                'db_table': 'tbl_document',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('middlename', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=45)),
                ('contact_no', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('registered_date', models.DateTimeField(blank=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('office_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.office')),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='ActivityLogs',
            fields=[
                ('no', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(blank=True)),
                ('activity', models.CharField(max_length=20)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackIt_app.user')),
            ],
            options={
                'db_table': 'tbl_activity_logs',
            },
        ),
    ]
